# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-consumer
  namespace: sb-queue-consumer
  labels:
    app: sb-consumer
spec:
  selector:
    matchLabels:
      app: sb-consumer
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sb-consumer
        azure.workload.identity/use: "true"  # Required for WorkloadIdentity. Only pods with this label can use workload identity.
    spec:
      serviceAccountName: sa-sb-queue-consumer # Required for WorkloadIdentity, Service Account must map to User Assigned Managed Identity (UAMI) in Azure.
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name: sb-consumer
        image: isaru66/springboot-azure-servicebus-consumer:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        env:
        - name: AZURE_SERVICEBUS_ENTITY_TYPE
          value: queue
        - name: AZURE_SERVICEBUS_QUEUE
          value: "queue-1"
        ports:
        - containerPort: 8080
          name: sb-consumer
      restartPolicy: Always
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: sb-consumer
  namespace: sb-queue-consumer
spec:
  selector:
    app: sb-consumer
  type: ClusterIP
  ports:
  - name: sb-consumer
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: "2ff650e6-e203-4246-b1cc-a241037bb841" # UMI Client ID
  name: "sa-sb-queue-consumer"
  namespace: "sb-queue-consumer"