FROM mcr.microsoft.com/openjdk/jdk:21-mariner

# Continue with your application deployment
RUN mkdir /opt/app
COPY target/azure-servicebus-producer-sample-0.0.1-SNAPSHOT.jar /opt/app/app.jar
CMD ["java", "-jar", "/opt/app/app.jar"]